### ISSUE TITLE
About the predicted threshold T

### ISSUE THREAD

**Issue by Dream-High** [moucheng2017/EMSSL#3]
In your paper, the predicted T seems to a scalar value. However, the predicted T in the code is a vector value. I have a little confuse about  this. Could you please tell me more details about this point.
![image](https://user-images.githubusercontent.com/28179137/221073730-8159e3d3-cbfa-41a3-8488-bd94696ede98.png)

**Comment by moucheng2017** [comment]
Thanks for pointing this out! In our old unpublished developing code we used AdaptiveAvgPool, it is a bug that this current version of code doesn't have it. 

I am re-factoring the code right now and will update it soon. By the way, I am adding a new small trick to avoid tuning the mu and logvar, that will also be included in the new version.
